title: "blog test: might or might not post articles eventually"
email: "your-email@example.com"
description: "My personal blog"
baseurl: ""
url: "https://graveljoly.github.io"
theme: minima
plugins:
  - jekyll-feed
